packages:
  - tinytacoteam/dotties-mouse
  - tinytacoteam/dotties-javascript
  - tinytacoteam/dotties-vim
  - tinytacoteam/dotties-git
  - tinytacoteam/dotties-vim-movements
  - tinytacoteam/dotties-tmux-movements
ignore:
  - readme.md
  - gpg.md
  - LICENSE
