packages:
  - tinytacoteam/dotties-mouse
  - tinytacoteam/dotties-javascript
  - tinytacoteam/dotties-oh-my-zsh
  - tinytacoteam/dotties-vim
  - tinytacoteam/dotties-git
ignore:
  - readme.md
  - gpg.md
  - LICENSE
bin:
  - bin/git-ca
  - bin/replace
