packages:
  - bayleeadamoss/dotties-mouse
  - bayleeadamoss/dotties-javascript
  - bayleeadamoss/dotties-vim
  - bayleeadamoss/dotties-git
  - bayleeadamoss/dotties-vim-movements
  - bayleeadamoss/dotties-tmux-movements
ignore:
  - readme.md
  - gpg.md
  - LICENSE
  - laptop.sh
